/** @format */

import { Form, Radio, Typography } from "antd";
import { useAxios } from "app/Hooks";
import { Buttonx, InputField, Toast } from "app/shared";
import { TooltipX } from "app/shared/ToolTip";
import { useEffect } from "react";
import { endpoints } from "static";

const { Text } = Typography;
const { NUMBER_PREFERENCES, SKU } = endpoints;

export const SkuForm = ({
  detail,
  handleClose,
  tooltipOverlayClass,
}: {
  detail: any;
  tooltipOverlayClass?: string | "";
  handleClose?: () => any;
}) => {
  const [form] = Form.useForm();
  const { callAxios, toggle, bool } = useAxios();
  const skuTermsBValue = Form.useWatch("skuTerms", form);
  useEffect(() => {
    form.setFieldsValue({
      skuTerms: detail?.terms,
      skuFormat: detail?.preferences?.skuFormat,
      startFrom: detail?.preferences?.startFrom,
    });
  }, [form, detail]);

  const handleSubmit = (values) => {
    toggle();
    callAxios({
      method: "put",
      url: `${NUMBER_PREFERENCES}${SKU}`,
      data: { ...values },
    })
      .then((res) => {
        if (res) {
          Toast({ message: res.message });
          handleClose?.();
        }
      })
      .catch(() => toggle());
  };
  return (
    <>
      <div className="_container sku_form main_wrapper">
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          <div className="form_box">
            <Form.Item
              colon={false}
              name="skuTerms"
              labelAlign="left"
              className="mb-10"
              label={<label className="color-1616">SKU</label>}
            >
              <Radio.Group defaultValue="auto">
                <div className="radio_group">
                  <Radio value="auto" className="align_label">
                    <Text>Auto generate SKU Number </Text>
                    <TooltipX
                      overlayClassName={tooltipOverlayClass}
                      placement="right"
                      title="This option will auto-generate the SKU. User can also provide the prefix (optional)"
                    >
                      <img
                        alt="tooltip Icon"
                        className="hover-effect pl-9"
                        src={`${
                          import.meta.env.VITE_AWS_S3_IMS_BUCKET_URL
                        }/static/media/tooltip.svg`}
                      />
                    </TooltipX>
                  </Radio>
                </div>
                <div className="radio_group mb-15">
                  <Radio value="manual" className="align_label">
                    <Text>Continue from last SKU Number</Text>
                    <TooltipX
                      overlayClassName={tooltipOverlayClass}
                      // zIndex={1101}
                      placement="right"
                      title="The SKU on latest products will be generated by incrementing the latest SKU in existing products list. Best suitable when importing products list to SeeBiz Books"
                    >
                      <img
                        alt="tooltip Icon"
                        className="hover-effect pl-9"
                        src={`${
                          import.meta.env.VITE_AWS_S3_IMS_BUCKET_URL
                        }/static/media/tooltip.svg`}
                      />
                    </TooltipX>
                  </Radio>
                </div>
              </Radio.Group>
            </Form.Item>
            <div className="flexbox ">
              <div className="form_group w-100 ">
                <InputField
                  form={form}
                  type="text"
                  maxLength={3}
                  size="middle"
                  name="skuFormat"
                  style={{ width: 232 }}
                  className="input_field"
                  label={<label>SKU Prefix</label>}
                />
              </div>
              {skuTermsBValue !== "manual" && (
                <div
                  className={`form_group w-100  ${
                    detail?.preferences?.startFromLocked ? "disabled" : ""
                  }`}
                >
                  <InputField
                    type="text"
                    size="middle"
                    name="startFrom"
                    style={{ width: 232 }}
                    className="input_field"
                    label={<label>SKU Start From</label>}
                    disabled={detail?.preferences?.startFromLocked}
                  />
                </div>
              )}
            </div>
            <div className="_sku_actions">
              <Buttonx
                btnText="Save"
                loading={bool}
                className="w-90 h-36 btn-form-size btn-primary text-center sku_form_btn"
              />
            </div>
          </div>
        </Form>
      </div>
    </>
  );
};
