export const Content = {
  sign_up_header: "Sign Up to Books",
  sign_in_header: "Sign In to Books live",
  forget_password: "Forget Password",
  reset_password: "Reset Password",
  already_have_code: "Already have an Code",
  aleady_have_account: "Already have an Account ?",
  dont_have_account: "Dont have an Account ?",
  congratulations: "Welcome to Books Managment System",
  account_verified: "Your Account Verified Successfully!",
  account_not_verified: "Account Verification Failed. Please try Later!",
  password_field_required: "please enter your password!",
  enter_confirmation_code: "please enter confirmation code!",
  enter_confirm_password: "please enter confirm password!",
  enter_your_name: "please enter name!",
  currency: "Currencies",
  enter_name: "Name is required",
  enter_options: "Options is required",
  enter_payment_method_name: "Payment method name is required",
  enter_currency_code: "Currency code is required",
  enter_symbol: "Symbol is required",
  enter_business_name: "Business name is required",
  enter_organization_type: "Industry is required",
  enter_time_zone: "Time zone is required",
  enter_fiscal_year: "Fiscal year is required",
  enter_base_currency: "Currency is required",
  enter_country_name: "Country is required",
  enter_phone: "Phone No. is required",
  enter_rate: "Rate is required",
  enter_account_name: "Account name is required",
  enter_account_group: "account group is required",
  enter_opening_balance: "opening balance is required",
  enter_current_balance: "current balance is required",
  all_items: "All Items",
  all_estimates: "All Estimates",
  add_notes: "Add notes",
  customer_notes: "Looking forward for your business",
  notes: "Looking forward for your business",
  terms_and_conditions:
    "Enter the terms and conditions of your business to be displayed in your transaction",
  billing_address: "Enter the billing address of your business to be displayed in your transaction",
  select_salesperson: "Select salesperson",
  estimate_number: "Select estimate number",
  reference_number: "Enter reference number",
  payment_terms: "Select payment terms",
  select_customer: "Select Customer",
  all_invoices: "All Invoices",
  new_recurring_invoice: "New Recurring Invoice",
  all_recurring_invoices: "All Recurring Invoices",
  all_credit_notes: "All Credit Notes",
  record_payment: " All Payment Receipts",
  all_purchase_orders: "All Purchase Orders",
  all_bills: "All Bills",
  all_bill_payments: "All Bill payments",
  all_sale_orders: "All Sale Orders",
  enter_role_name: "Enter Role Name",
  role_name_required: "Role name is required",
  permissions_required: "please select atleast one role permission",
  role_required: "Role is required",
  compound_tax: "Add as Compound Tax",
  unit_required: "Unit is required",
  sku_required: "SKU is required",
  generate: "Generate SKU",
  duration: "Duration",
  selling_price_required: "selling price is required",
  sales_account_required: "Sales account is required",
  purchase_price_required: "purchase price is required",
  purchase_account_required: "Purchase account is required",
  all_packages: "All Packages",
  package_required: "package no is required",
  sales_order_required: "sales order is required",
  select_item: "please select atleast one item",
  select_sales_order: "Please Select a Sales Order",
  bill_no_required: "bill no. is required",
  order_no_required: "order no. is required",
  select_vendor: "Select Vendor",
  purchase_order_required: "Purchase order no is required",
  select_warehouse: "Select Warehouse",
  estimate_no_required: "estimate no is required",
  select_terms: "Select Terms",
  select_item_type: "Select Item Type Goods or Service",
  item_measured_term: "The Item will be measured in terms of this unit",
  select_unit: "Select/Add selling unit",
  stock_keeping_unit: "The Stock Keeping Unit of Item",
  select_sales_account: "Select income account",
  select_purchase_account: "Select Purchase Account",
  item_tax_tooltip:
    "Add Tax to your Item. Add Tax Group if you are planning to add more than one Tax.",
  department_name: "Department Name",
  first_name_required: "First name is required",
  last_name_required: "last name is required",
  display_name_required: "display name is required",
  inventory_tootip:
    "Enable inventory to track this item's stock based on the sales and purchase transactions recorded in your business",
  all_recurring_bills: "All Recurring Bills",
  enter_company_name: "Company name is required",
  my_legal_bussiness_name: "This is my legal business name",
  prefernece_bill_number_warning:
    "Warn me when I enter a bill number that’s already been used for that supplier",
  make_expense_and_item_billable: "Make expense and Products billable",
  expense_and_item_billable_tooltip:
    "Adds a billable coulmn in expense and purchase forms so you can add billable expenses and items on sales forms",
  term_and_condition_to_be_displayed: "Terms and conditions to be displayed on bill",
  product_and_services: "Products & Services",
  enter_terms_conditions: "Enter terms and conditions",
  reason_required: "please enter any one reason in this field",
  expense: "Expense",
  emailConfirm: "Do you really want to discard this message?",
  clearLinesConfirm: "Do you really want to clear all lines?",
  setDefaultConfirm: "Do you really want to set this business as default?",
  findByInvoicePop:
    "You can either use the 'Customer' dropdown or 'Find by invoice no'. to start the payment process ",
  calculatedTranaction: "This transactions will create an additional credit in the amount of",
  paymentFilterPop:
    "If you've entered a payment amount for any unpaid invoices,those invoices will continue to be shown at the top of the list, irrespective of the date and status filters that you apply",
  totalChargesPop: "This is the sum of payment values for the invoices you have selected",
  ExpenseAccountPop:
    "For inventory products, we will only show those accounts which have subtype Inventory.For non-inventory products,we will only show those accounts which have the category Expenses",
  shared_modules_info:
    "Products & Services, Customer & Supplier, Estimates are available by default in Seebiz Books.",
  enter_account_category: "Account category is required",
  select_parent_account: "Parent account is required",
  select_category: "Category is required",
  select_amount: "Amount is required",
  select_date: "Date is required",
  select_selling_unit: "Selling unit is required",
  select_inventory_account: "Inventory asset account is required",
  select_income_account: "Income account is required",
  select_expense_account: "Expense account is required",
  enter_reason: "Reason is required",
  select_inventory_adjustment: "Inventory adjustment account is required",
  enter_company_phone: "Company phone is required",
  select_llc: "LLC is required",
  select_business_type: "Business type is required",
  select_date_range: "Date range is required",
  select_payment_method: "Payment method is required",
  enter_receive_no: "Receive No. is required",
  enter_profile_name: "Profile Name is required",
  select_repeat_duration: "Repeat Every is required",
  enter_attention: "Attention is required",
  enter_street_1: "Street 1 is required",
  enter_street_2: "Street 2 is required",
  enter_value: "Value is required",
  enter_payment_received: "Payment received is required",
  enter_invoice_no: "Invoice No. is required",
  enter_amount_received: "Amount received is required",
  character_length: "No more than 15 Characters.",
};
