/** @format */

export const Labels = {
  LOGIN: "Login",
  SIGNUP: "SIGNUP",
  EMAIL: "Email",
  _EMAIL: "email",
  PASSWORD: "Password",
  ENTER: "Enter",
  FORGET: "Forget",
  GENDER: "gender",
  REMEMBER_ME: "Remember me",
  SUBMIT: "Submit",
  SIGNIN: "Sign In",
  CODE: "Code",
  CONFIRM_PASSWROD: "Confirm Password",
  NAME: "Name",
  _NAME: "name",
  REGISTER_ORGANIZATION: "register-organization",
  CREATE: "Create",
  BACK: "Back",
  NEXT: "Next",
  TYPE: "Type",
  TIMEZONE: "Time zone",
  FISCAL_YEAR: "Fiscal year",
  BASE_CURRENCY: "Currency",
  LICENSE_NO: "License No.",
  START_DATE: "Start Date",
  CONTACT: "Contact",
  COUNTRY: "Country",
  STATE: "  State/Province",
  CITY: "City",
  ZIP_CODE: "ZIP code",
  ADDRESS: "Street address",
  PHONE: "Phone No.",
  WEBSITE: "Website",
  COMPANY_WEBSITE: "Company website",
  NEW_CURRENCY: "New Currency",
  CURRENCY_CODE: "Currency Code",
  SYMBOL: "Symbol",
  EXCHANGE_RATE: "Rate",
  CANCEL: "Cancel",
  YES: "Yes",
  NO: "No",
  DELETE: "Delete",
  _CURRENCY: "Currency",
  SET_AS_DEFAULT: "Set as Default",
  OWNER: "Owner",
  INVITEE: "Invitee",
  BUSINESS_INFO: "Business Info",
  CONTACT_INFO: "Contact Info",
  BUSINESS_NAME: "Business name",
  TAX: "Tax",
  ACCOUNT: "Account",
  ACCOUNT_TYPE: "Account type",
  _ACCOUNT_NAME: "Account name",
  RATE: "Rate",
  AUTHORITY: "Authority",
  NEW_TAX: "New Tax",
  NEW_ACCOUNT: "New Account",
  GROUP: "Group",
  TAX_RATE: "Tax Rates",
  _ACCOUNT_GROUP: "Account Group",
  USERS_ROLES: "Users & Roles",
  PDF_PREFERENCES: "Pdf Preference",
  HOME: "Home",
  _ORGANIZATION_PROFILE: "Organization Profile",
  _WAREHOUSE: "Warehouse",
  _TAXES: "Taxes",
  _ACCOUNTS: "Accounts",
  _ITEMS: "Items",
  NEW_ITEM: "New Item",
  _ESTIMATES: "Estimates",
  BILLS: "Bills",
  NEW_ESTIMATE: "New estimate",
  NEW_BILL: "New bill",
  _CUSTOMERS: "Customers",
  COMPANY_NAME: "Company name ",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  OPENING_BALANCE: "Opening Balance",
  CURRENT_BALANCE: "Current Balance",
  NEW_INVOICE: "New Invoice",
  NEW_RECURRING_INVOICE: "New Recurring Invoice",
  _INVOICES: "Invoices",
  NEW_CREDIT_NOTE: "New Credit note",
  NEW_PAYMENT_METHOD: "New Payment Method",
  _PAYMENT_METHODS: "Payment Methods",
  _PAYMENT_METHOD: "Payment Method",
  NEW_PAYMENT_RECEIVED: "New payment receipt",
  BANK_CHARGES: "Bank Charges (if any)",
  NEW_PURCHASE_ORDER: "New Purchase Order",
  _PURCHSE_ORDERS: "PurchaseOrders",
  _SALES_ORDERS: "SalesOrders",
  NEW_SALE_ORDER: "New Sale Order",
  UPDATE: "Update",
  ROLE: "Role",
  _ROLE: "role",
  EDIT: "Edit",
  SALES_PERSON: "Sales Person",
  View: "View",
  INVITE: "Invite",
  USER: "User",
  NEW: "New",
  GOODS: "Goods",
  SERVICE: "Service",
  UNIT: "Unit",
  SKU: "SKU",
  SELLING_PRICE: "Sale price/rate",
  DESCRIPTION: "Description",
  PURCHASE_PRICE: "Purchase Price",
  UNIT_PRICE: "Unit Price",
  DETAILS: "Details",
  DATE: "Date",
  AMOUNT: "Amount",
  BALANCE: "Balance",
  END_DATE: "End Date",
  PAYMENTS: "Payments",
  TRANSACTION: "Transaction",
  TRANSACTION_TYPE: "Transaction Type",
  TRANSACTION_NUMBER: "Transaction Number",
  NEW_PACKAGE: "New Package",
  PACKAGE_NO: "Package No",
  PACKAGE_DATE: "Package Date",
  SALES_ORDER: "Sales Order",
  _PACKAGES: "Packages",
  EDIT_PACKAGE: "Edit Package",
  CREATE_PACKAGE: "Create Package",
  EDIT_INVOICE: "Edit Invoice",
  CREATE_INVOICE: "Create Invoice",
  UPDATE_CURRENCY: "Update Currency",
  SALES_ORDER_NO: "Sales Order No.",
  REFERENCE: "Reference",
  REFERENCE_NO: "Reference number",
  STATUS: "Status",
  INVOICE_NO: "Invoice number",
  PAYMENT_DUE: "Payment Due",
  PAYMENT_NO: "Payment No",
  CREDIT: "Credit",
  INVOICE: "Invoice",
  QUANTITY: "Quantity",
  CREDIT_NOTE: "Credit note",
  SALES_RETURN: "Sales Return",
  ADD_TO_STOCK: "Add to Stock",
  RECEIVE_DATE: "Receive Date",
  RECEIVE_ITEMS_TYPE: "Receive Items Type",
  EDIT_BILL: "Edit Bill",
  CREATE_BILL: "Create Bill",
  VENDOR: "Vendors",
  BILL_DATE: "Bill Date",
  ADJUSTMENT: "Adjustment",
  DEPOSIT: "Deposit",
  ADJUSTMENT_TYPE: "Adjustment type",
  EXPIRY_DATE: "Expiry Date",
  ORDER_NO: "Order number",
  BILL_NO: "Bill No.",
  NOTES: "Notes",
  TERMS_AND_CONDITIONS: "Terms and conditions",
  BILLING_ADDRESS: "Billing address",
  PURCHASE_ORDER_NO: "Purchase Order No.",
  DELIVERY_DATE: "Delivery Date",
  ESTIMATE_DATE: "Estimate Date",
  CUSTOMER_NOTES: "Customer Notes",
  SHIPPING_CHARGES: "Shipping charges",
  SALESPERSON: "Salesperson",
  INVOICE_DATE: "Transaction date",
  DUE_DATE: "Due Date",
  CUSTOMER_TYPE: "Customer Type",
  SALUTATIONS: "Salutation",
  DEPARTMENT: "Department",
  MOBILE: "Mobile",
  DESIGNATION: "Designation",
  DISPLAY_NAME: "Display Name",
  FAX: "Fax",
  STREET: "Street",
  ATTENTION: "Attention",
  COUNTRY_NAME: "Country Name",
  DUE: "Due",
  RECEIVE_NO: "Receive No.",
  OPENING_STOCK: "Opening Stock",
  PHYSICAL_STOCK: "Physical Stock",
  ACCOUNTING_STOCK: "Accounting Stock",
  REASON: "Reason",
  ADJUSTED_QTY: "Adjusted Qty",
  USER_NAME: "User Name",
  INVITATION: "Invitation",
  QTY: "QTY",
  TOTAL: "Total",
  CUSTOMER: "Customer",
  LINKS: "Links",
  STOCK_VALUE: "Opening Stock Value (Per Unit)",
  REORDER_POINT: "Reorder point",
  NEW_RECURRING_BILL: "New Recurring Bill",
  RECURRING_BILLS: "Recurring Bills",
  PROFILE_NAME: "Profile Name",
  RECURRING: "Recurring",
  START_ON: "Start On",
  ENDS_ON: "Ends On",
  PAYMENT_TERMS: "Payment Terms",
  REPEAT_EVERY: "Repeat Every",
  ROLE_INFO: "Role Info",
  IS_SALES_PERSON: "Is sales person?",
  SAVE: "Save",
  LEGAL_NAME: "Legal Name",
  TAX_FORM: "Tax Form",
  COMPANY_EMAIL: "Company email",
  COMPANY_PHONE: "Company phone",
  MANAGE_BUSINESSES: "Manage Businesses",
  PAYMENT_TERM_ID_PLACEHOLDER: "Select default bill payment terms",
  DEFAULT_BILL_PAYMENT_TERMS: "Default bill payment terms",
  CREDIT_NOTE_DEDUCTION_POLICY: "Credit note deduction Policy",
  CREDIT_NOTE_DEDUCTION: "Enable Credit note deduction",
  DEDUCTION_TYPE: "Deduction Type",
  DEDUCTION_VALUE: "Deduction value",
  SELECT_TIME_PERIOD: "Select time period",
  SALES_INFORMATION: "Sales information",
  PACKAGE_AND_SHIPMENT: "Package & shipment",
  PURCHASE_INFORMATION: "Purchase information",
  RECEIVABLES: "Receivables",
  PAYABLES: "Payables",
  TOP_SELLING_ITEM: "Top selling Products",
  TOP_CUSTOMER: "Top customers",
  SALES_VS_PURCHASE: "Sales vs purchase",
  SALES_ORDER_SUMMARY: "Estimates summary",
  NEW_PRODUCT: "New Product",
  PRODUCT_CATEGORIES: "Product Categories",
  NEW_CATEGORY: "New Category",
  CREATE_CATEGORY: " Add New Product Category",
  SELECT_PRODUCT_TYPE: "Select product type",
  PRODUCT_DESCRIPTION: "Product description",
  MPN: "MPN",
  EAN: "EAN",
  ISBN: "ISBN",
  COST: "Cost",
  BRAND: "Brand",
  WEIGHT: "Weight",
  CATEGORY: "Category",
  ADD_NOTES: "Add notes",
  SALES_TAX: "Sales tax",
  DIMENSIONS: "Dimensions",
  UPC_BARCODE: "UPC/Barcode",
  MANUFACTURER: "Manufacturer",
  INCOME_ACCOUNT: "Income account",
  EXPENSE_ACCOUNT: "Expense account",
  SALES_DESCRIPTION: "Sales description",
  INITIAL_QUANTITY: "Initial quantity on hand",
  PURCHASE_DESCRIPTION: "Purchasing information",
  SELECT_PRODUCT_CATEGORY: "Select product category",
  UPDATE_CATEGORY: "Update Product Category",
  LOCATION: "Location",
  QUANTITY_ADJUSTED: "Quantity Adjusted",
  SELLING_UNIT: "Selling unit",
  TAG_NAME: "Tag Name",
  upload_product_image: "Upload product image",
  Attachment: "Attachment",
  EXPENSE: "Expenses",
  NEW_EXPENSE: "New Expense",
  // TAG_NAME: "Tag Name",
  INDUSTRY: "Industry",
  PRODUCTS_SERVICES: "Products & Services",
  ESTIMATE_NO: "Estimate number",
  REFERENCE_NUMBER: "Reference number",
  PURCHASE_TAX: "Purchase tax",
  PREFERRED_SUPPLIER: "Preferred supplier",
  BILL_PAYMENTS: "Bill payments",
  CREATE_ACCOUNT: "Create New Account",
  MAP_ACCOUNT: "Map Old Account",
  EDIT_ACCOUNT: "Edit Account",
  ACCOUNT_SUB_TYPE: "Sub-type",
  ACCOUNT_NO: "Account No.",
  BANK_ACCOUNT_NO: "Bank Account Number",
  TAX_CODE: "Tax Code",
  CHART_OF_ACCOUNTS: "Chart of accounts",
  ESTIMATES_INFORMATION: "Estimates information",
};
